### PR TITLE
Add poll command

### PR DESCRIPTION
**Pull request by maximilian-franz**
This PR, together with https://github.com/MTrab/landroid_cloud/pull/76, adds the ability to force poll status information of a lawn mower. This can be useful for example to get status information between regular status updates.

### CODE REVIEW

**Comment by MTrab** [comment]
Idea is great, but need some way of throtteling, as too many polls in a given timeframe would get you banned

**Comment by maximilian-franz** [comment]
> 
> 
> Idea is great, but need some way of throtteling, as too many polls in a given timeframe would get you banned

Yes you are right. I am planning to use the `ratelimit` module for that and it seems to be working.
However, I am not sure where to add this as a requirement, since there's [Requirements.txt](https://github.com/MTrab/pyworxcloud/blob/master/Files/Requirements.txt) and
```python
requirements = ['paho-mqtt==1.5.0',
                'pyOpenSSL==17.5.0']
```
[setup.py](https://github.com/MTrab/pyworxcloud/blob/master/setup.py).

Also, do you happen to know the rate limit by any chance? If not, I'd go with 1 poll/min for now.

**Comment by MTrab** [comment]
Much better - the Requirements.txt are solely for my own notes. Should actually be deleted ;)
Regarding the rate limit - somewhere, in a Messenger conversation with a Worx technician I have the suggested max rate. Will see if I can find it again.

**Comment by maximilian-franz** [comment]
> 
> 
> Much better - the Requirements.txt are solely for my own notes. Should actually be deleted ;)
> Regarding the rate limit - somewhere, in a Messenger conversation with a Worx technician I have the suggested max rate. Will see if I can find it again.

Did you find it yet? 😅

**Comment by MTrab** [comment]
Need to have these conflicts sorted before merge

**Comment by maximilian-franz** [comment]
All conflicts should be resolved now.

**Pull request merged**
